// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      env: {
        dev: {
          NODE_ENV: 'development',
          PORT: 8080
        },
        simple: {
          NODE_ENV: 'development',
          PORT: 8080
        }
      },
      mochaTest: {
        test: {
          options: {
            reporter: 'spec',
            require: 'coffee-script',
            mocha: require('mocha')
          },
          src: ['server/test/**/*_test.js']
        }
      }
    });
    grunt.registerTask('test', ['env:dev', 'mochaTest']);
    grunt.registerTask('test_simple', ['env:simple', 'mochaTest']);
    grunt.loadNpmTasks('grunt-mocha-test');
    return grunt.loadNpmTasks('grunt-env');
  };

}).call(this);
