// Generated by CoffeeScript 1.7.1
(function() {
  var ENV_PORT, async, config, request, server, serverHelper, should;

  request = require('supertest');

  should = require('should');

  async = require('async');

  serverHelper = require('../helpers/server');

  config = require('config');

  server = null;

  ENV_PORT = process.env.PORT || 8080;

  console.log(ENV_PORT);

  describe('Test Route', function() {
    var url;
    url = 'http://localhost:' + ENV_PORT;
    return describe('#/test [GET] multiple times series', function() {
      return async.each([0, 1, 2], function(i) {
        return it("should return 200 and Object of status #" + i + " attempt", function(done) {
          return request(url).get("/api/test").expect('Content-Type', /json/).expect(200).end(function(err, res) {
            if (err) {
              throw err;
            }
            res.body.should.be.an.instanceOf(Object);
            res.body.should.have.property('message');
            return done();
          });
        });
      }, function(error) {
        if (error) {
          throw error;
        }
        return console.log("AHA");
      });
    });
  });

}).call(this);
