# have to be indented by spaces!!

logger:
    console_log_level: debug
    file_log_level: WARN

db:
    host: '127.0.0.1'
    user: 'root'
    password: 'root'
    port: 3306
    # socketPath: '/opt/boxen/data/mysql/socket' # uncoment when you wanna use socket path
    database: 'gpsgsm'
    timezone: 'Z'

main:
    listen_ip: '127.0.0.1'
    listen_port: 3000
    key: '/etc/ssl/self-signed/server.key'
    cert: '/etc/ssl/self-signed/server.crt'
    ca: '/etc/ssl/self-signed/intermediate.crt'
    maxSockets: 15
    baseURL: 'http://localhost:3000'