// Generated by CoffeeScript 1.7.1
(function() {
  var ENV_PORT, config, io, options, server, serverHelper, should;

  should = require('should');

  io = require('socket.io-client');

  serverHelper = require('../helpers/server');

  config = require('config');

  server = null;

  ENV_PORT = process.env.PORT || config.main.listen_port;

  options = {
    transports: ['websocket'],
    'force new connection': true
  };

  describe('Test Socket', function() {
    var url;
    url = 'http://localhost:' + ENV_PORT;
    before(function(done) {
      return server = serverHelper.createServer(done);
    });
    after(function(done) {
      server.close();
      console.log("test server closed");
      return done();
    });
    return it('#should emit test.response socket', function(done) {
      var client;
      client = io.connect(url, options);
      return client.on('connect', function(data) {
        client.emit('test', {
          title: "Testing",
          body: "testing body"
        });
        return client.on('test.response', function(data) {
          data.should.be.an.instanceOf(Object);
          data.should.have.property('title');
          data.should.have.property('body');
          return done();
        });
      });
    });
  });

}).call(this);
