// Generated by CoffeeScript 1.7.1
(function() {
  var app, config, createServer, getHeaders;

  app = require('../../tier_ui/app').api;

  config = require('config');

  module.exports = {
    createServer: function(done) {
      return createServer(done);
    },
    getHeaders: function(type, path) {
      return getHeaders(type, path);
    },
    getBaseUrl: function() {
      return getBaseUrl();
    }
  };

  createServer = function(done) {
    var server;
    server = require('http').createServer(app);
    require('../../tier_ui/socket_app')(app, server);
    return server.listen('3000', function(error, result) {
      if (error) {
        return done(error);
      } else {
        return done();
      }
    });
  };

  getHeaders = function(type, path) {
    var headers;
    return headers = {
      "host": "127.0.0.1",
      "port": '3000',
      "path": path,
      "method": type,
      "headers": {}
    };
  };

}).call(this);
